### ISSUE TITLE
Poor-to-no LaTeX recognition/rendering

### ISSUE THREAD

**Issue by Attelisk** [ZachSaucier/Just-Read#58]
JustRead attempts to parse LaTeX images but fails. Installing Tex The World for Chromium doesn't seem to help.

Here's what I get

![image](https://cloud.githubusercontent.com/assets/26373084/23841876/65401a0a-07eb-11e7-8a37-259c4305335e.png)

Here's the original representation:

![image](https://cloud.githubusercontent.com/assets/26373084/23841919/ce9cd0f6-07eb-11e7-8718-a57b8d4cb696.png)

**Comment by ZachSaucier** [comment]
Thanks for the report! While JustRead doesn't support native LaTeX, it should still select the backup image version of it. It wasn't because of some overly-eager deletion JustRead was doing. I've fixed that now.

Tell me, if only the image version is shown, would you expect to see the plain text version alongside the image so it could be copy-able, or would you be alright with going back to the original article if you wanted to do that?

**Comment by Attelisk** [comment]
I still can't see those back-up images. I've re-installed JustRead and the above still displays the same.

As for your question about the text, I think being able to read the text comfortably is far more important than being able to being able to copy from within the JustRead interface.

That being said, perhaps it might be a nice feature to have a button on the left (or right) hand side that you can click/hover over to display the plaintext for LaTeX images? I'm not sure how difficult that would be to implement, but that would be the only case I would prefer having the text on-screen.

**Comment by ZachSaucier** [comment]
Yes, sorry, I meant that I had implemented them but not pushed the changes because I was waiting on your feedback :)

I'll look into showing the plain text on hovering.

**Comment by Attelisk** [comment]
Oh ok! Please let me know when/if either are implemented. Also, thanks for the prompt reply!

**Comment by ZachSaucier** [comment]
As of JR version 1.0.23, LaTeX images should be shown with the plain text version being shown on hover. It'll take ~1 hour for it to update in the Chrome store, but after that you can force your version to update or wait until Chrome auto-updates it a little later.

**Comment by ZachSaucier** [comment]
For future reference, this issue was only the case on Wikipedia of the LaTeX pages I tested. Something weird about their format (that I did not determine) was messing up Just Read's selection of the LaTeX content.

**Comment by ZachSaucier** [comment]
Version 1.1.1 has improved MathJax support (mostly non-Wikipedia sites).
